# Generated by Django 2.2.5 on 2020-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=2)),
                ('Designation', models.CharField(max_length=70)),
                ('Location', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Qualification', models.CharField(max_length=20)),
                ('Experience', models.IntegerField()),
                ('Language', models.CharField(max_length=20)),
                ('Nationality', models.CharField(max_length=20)),
                ('year_of_passout', models.IntegerField()),
                ('job_type', models.CharField(max_length=20)),
                ('current_ctc', models.FloatField()),
                ('expected_ctc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JOB2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=64)),
                ('Eligibility', models.CharField(max_length=64)),
                ('Address', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
