# Generated by Django 2.2.5 on 2020-03-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_apply_job2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='mobile',
            new_name='Mobile',
        ),
    ]
